name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [18, 20]
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  docker-validate:
    name: docker-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker validate (placeholder)
        run: |
          echo "add your docker build/scan commands here"